#!/bin/sh

set -o noclobber
set -o errexit
set -o nounset

d="$(dirname "$(readlink "$0")")"

cd "$d"

echo "------- Getting matze/mtheme -------"
wget 'https://raw.githubusercontent.com/matze/mtheme/a54d7477a9d52a8ef62536c1faaa0dbf75e85b81/beamerthemem.sty'               -O 'beamerthemem.sty'
wget 'https://raw.githubusercontent.com/matze/mtheme/a54d7477a9d52a8ef62536c1faaa0dbf75e85b81/beamerfontthememetropolis.sty'  -O 'beamerfontthememetropolis.sty'
wget 'https://raw.githubusercontent.com/matze/mtheme/a54d7477a9d52a8ef62536c1faaa0dbf75e85b81/beamercolorthememetropolis.sty' -O 'beamercolorthememetropolis.sty'

sed -re 's/\{FiraSans Italic\}/\{FiraSans-Italic\}/g' -i 'beamerfontthememetropolis.sty'
sed -re 's/\{FiraSans Light Italic\}/\{FiraSans-LightItalic\}/g' -i 'beamerfontthememetropolis.sty'
sed -re 's/\{FiraSans\}/\{FiraSans-Medium\}/g' -i 'beamerfontthememetropolis.sty'
sed -re 's/\{FiraSans Light\}/\{FiraSans-Light\}/g' -i 'beamerfontthememetropolis.sty'
sed -re 's/\{FiraSans ExtraLight\}/\{FiraSans-ExtraLight\}/g' -i 'beamerfontthememetropolis.sty'
sed -re 's/\{FiraSans Mono\}/\{FiraMono-Medium\}/g' -i 'beamerfontthememetropolis.sty'

echo "------- Building main.pdf -------"
xelatex -shell-escape 'main.tex'
xelatex -shell-escape 'main.tex'
