#!/bin/sh

set -o noclobber
set -o errexit
set -o nounset

d="$(cd "$(dirname "$0")" ; pwd)"

curl -s 'https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt' -o "$d/sbt"
chmod 0700 "$d/sbt"

cd "$d"
./sbt stage

echo
echo "now, run ./question-generator --help"
