#!/bin/sh

set -o noclobber
set -o errexit
set -o nounset

d="$(cd "$(dirname "$0")" ; pwd -P)"
f="$d/target/universal/stage/bin/question-generator"

[ -x "$f" ] || {
  echo >&2 "run ./build first"
  exit 1
}

exec "$f" -- "$@"
